# Generated by Django 3.2.9 on 2021-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='movie',
        ),
        migrations.AddField(
            model_name='recommend',
            name='movie_pk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
